# Generated by Django 4.0.5 on 2022-06-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textboard', '0003_alter_board_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='description',
            new_name='verbose',
        ),
    ]
