# Generated by Django 4.0.5 on 2022-06-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='editor',
            new_name='editor_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='thread_id',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='editor',
            new_name='editor_id',
        ),
    ]
