# Generated by Django 4.0.5 on 2022-06-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_post_editor_id_alter_thread_editor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='editor_id',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='editor_id',
            new_name='editor',
        ),
    ]
