# Generated by Django 4.0.5 on 2022-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_post_creator_alter_post_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='editor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
